[package]
name = "libwizard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.0"
minify-html = "0.11.1"
owo-colors = "3.5.0"
tokio = { version = "1.29.1", features = ["full"] }
